logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "rs.test"
  watch = true
  exposedbydefault = false

[accessLog]

# Don't force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

################################################################
# File configuration backend
################################################################
# Enable file configuration backend
# Optional
# Mounted via TRAEFIK_PROVIDERS_FILE_FILENAME env var
[file]
  filename = "/etc/traefik/custom.toml"

# Enable watch file changes
  watch = true