logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "rs.test"
  watch = true
  exposedbydefault = false

 # Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    # entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

 # Let's encrypt configuration
#  [acme]
#    email="youremail.address@example.com"
#    storage="/etc/gateway/acme/acme.json"
#    entryPoint="https"
#    acmeLogging=true
#    OnHostRule=true
#    [acme.httpChallenge]
#      entryPoint = "http"

################################################################
# File configuration backend
################################################################
# Enable file configuration backend
# Optional
# Mounted via TRAEFIK_PROVIDERS_FILE_FILENAME env var
[file]
  filename = "/etc/gateway/custom.toml"

# Enable watch file changes
  watch = true